# -*- coding: utf-8 -*-
"""InstantMesh.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C_GMyC7XzLlR88oU5CdKH3WIswmaLS-i
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install -U diffusers
# !pip install gradio_client
# !pip install -U diffusers transformers accelerate
# !pip install gradio_client pillow requests google-colab

"""Now that `gradio_client` is installed, here's an example of how to use the `/preprocess` API endpoint. This will download an image, send it to the Gradio Space, and return the processed image."""

from google.colab import files
import os

print("Step 1: Upload your image file")
uploaded = files.upload()

if uploaded:
    input_path = list(uploaded.keys())[0]
    print(f"File uploaded: {input_path}")
else:
    raise ValueError("No file uploaded. Please upload an image to continue.")

import requests
from PIL import Image
from io import BytesIO

# @title Step 2: Remove Background (Remove.bg)
REMOVE_BG_API_KEY = "3SmQATau7ZtkEUozPLPexArH" # @param {type:"string"}

if not REMOVE_BG_API_KEY:
    print("No API key provided. Skipping background removal and using original image.")
    bg_removed_path = input_path
else:
    response = requests.post(
        'https://api.remove.bg/v1.0/removebg',
        files={'image_file': open(input_path, 'rb')},
        data={'size': 'auto'},
        headers={'X-Api-Key': REMOVE_BG_API_KEY},
    )
    if response.status_code == requests.codes.ok:
        bg_removed_path = "no_bg_image.png"
        with open(bg_removed_path, 'wb') as out:
            out.write(response.content)
        display(Image.open(bg_removed_path))
        print("Background removed successfully.")
    else:
        print("Error:", response.status_code, response.text)
        bg_removed_path = input_path

from gradio_client import Client, handle_file

# Step 3: Generate Multi-views
client = Client("SIGMitch/InstantMesh")

print("Generating multi-views...")
mvs_result = client.predict(
    input_image=handle_file(bg_removed_path),
    sample_steps=75,
    sample_seed=42,
    api_name="/generate_mvs"
)

print(f"Multi-view image generated at: {mvs_result}")
display(Image.open(mvs_result))

import shutil

# Step 4: Generate 3D Model
print("Generating 3D model (OBJ/GLB)...")
make3d_result = client.predict(
    api_name="/make3d"
)

# The result is usually a list containing paths to [obj_file, glb_file]
print("3D Model files generated:")
for file_path in make3d_result:
    filename = os.path.basename(file_path)
    shutil.copy(file_path, f"./{filename}")
    print(f"Saved: {filename}")

# Provide download links for the files
from google.colab import files as colab_files
for file_path in make3d_result:
    colab_files.download(os.path.basename(file_path))

"""Finally, let's call the `/make3d` API endpoint to generate the final 3D models (OBJ and GLB formats). This endpoint doesn't require any inputs."""

from gradio_client import Client

# Inspect the API to find the correct video endpoint
client = Client("SIGMitch/InstantMesh")
client.view_api()

"""Now, let's use the `/generate_mvs` API endpoint. This will take the `result` from the previous step (the processed image) as input and generate multi-views."""